DATA_FILES_LOCATION = '../References'

# Most Improved Batting Average
MOST_IMPROVED_START_YEAR = 2009
MOST_IMPROVED_END_YEAR = 2010
BATTING_AVG_MIN_AT_BATS = 200

# Slugging Percentage
SLUGGING_TEAM = 'OAK'
SLUGGING_YEAR = 2007

# Triple Crown
TRIPLE_CROWN_START_YEAR = 2011 
TRIPLE_CROWN_END_YEAR = 2012
TRIPLE_CROWN_LEAGUES = ['NL', 'AL']
TRIPLE_CROWN_MIN_AT_BATS = 400